import markov
import scraper
import json_generator

def main():
    
    song = input("What's the song you want to visualize? ")
    artist = input("And who's it by? ")

    lyrics = scraper.parse(song, artist)
    mc = markov.build_mkch(lyrics)
    json_generator.build_json(mc)

    
    # the list generated by the following print function is a text-based visualization of 
    # the markov chain (adjacency list)
    
    # each node (unique word) is listed with all its edges (words it links to), along with `the 'probability'
    # that a word in the edge-list follows the node
    markov.print_mkch(mc)

main()
